[package]
name = "spherical-wrist"
version = "0.0.3"
edition = "2024"
license = "BSD-3-Clause"

[lib]
name = "spherical_wrist"
crate-type = ["cdylib"]

[dependencies]
glam = "=0.32.1"
parry3d = "0.27"
pyo3 = "0.29"
rs-opw-kinematics = { version = "3", default-features = false, features = ["stroke_planning", "visualization"] }
rs-read-trimesh = { version = "= 2.0.10", features = ["use-parry-27"], default-features = false }
